---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: mundose
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx  
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: mundose
  labels:
    app: nginx
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    nodePort: 32180
  selector:
    app: nginx
  type: NodePort